### PR TITLE
Set passphrase only for the fingerprint being used

### PR DESCRIPTION
**Pull request by josecelano**
Relates to: https://github.com/crazy-max/ghaction-import-gpg/issues/119#issuecomment-1050066795

I had problems using a signing subkey. 

How to reproduce:

1. Create a new GPG key.
2. Create a subkey only for signing.
3. Remove signing usage to the primary key.
4. Export only signing subkey. The exported key contains the primary key but you can not use it.
5. Import the subkey in a temp GPG home dir.
6. CHange the passphrase for the key.

That is the process to upload a signing subkey to GitHub with a different passphrase.

Using that key this action tries to preset the passphrase for all the subkeys, including the primary key. Since the primary key is not functional I got an error. I have changed the code to only preset the key for the subkey if you specify the input `fingerprint`.

I've tested the change in this repo: https://github.com/Nautilus-Cyberneering/chinese-ideographs-website/runs/5336330660?check_suite_focus=true#step:4:40

### CODE REVIEW

**Comment by josecelano** [comment]
> @josecelano Thanks for this! A test seems to fail: https://github.com/crazy-max/ghaction-import-gpg/runs/5336379690?check_suite_focus=true#step:4:337

It was only a temp test to give an example. I've used a key from my keyring. I was afraid that the tests could change things in my personal keyrgrip because I do not see where you overwrite the GPG homedir for the tests. I thought a maintainer could move the test for the new function to the `gpg.test.ts` file before merging the PR. I can do it but then It will take me more time because I have to load the test key and add the subkeys fingerprints to `userInfos`.

**Comment by josecelano** [comment]
By the way @crazy-max I'm using part of the code on this repo [here](https://github.com/Nautilus-Cyberneering/git-queue#credits). Although we might remove the signing feature from that action in the future.

**Review by crazy-max — APPROVED** [review]
LGTM thanks! I wonder if you could add an example using a subkey and a specific fingerprint in usage section of the README https://github.com/crazy-max/ghaction-import-gpg#usage?

**Comment by crazy-max** [comment]
Oh and also add a new job in https://github.com/crazy-max/ghaction-import-gpg/blob/master/.github/workflows/ci.yml to test that behavior as e2e test if you want but not required.

**Review by crazy-max — APPROVED** [review]
Awesome thanks!

**Pull request merged**
